context:
  name: "fastjet-contrib"
  version: "1.101"

recipe:
  # Have top level name be unique from any outputs
  # c.f. https://github.com/conda-forge/conda-forge.github.io/blob/abfc33db28c35e9a8f6b719d0021768f0d5d06be/docs/maintainer/knowledge_base.md?plain=1#L1749
  name: ${{ name }}-split
  version: ${{ version }}

source:
  url: https://fastjet.hepforge.org/contrib/downloads/fjcontrib-${{ version }}.tar.gz
  sha256: dbe8ad2199f72d64dd29f6218f6f53efddc8fb3e5dd9c5d10f2fd1e23d6e44f6
  patches:
    - 0001-top-level-only-cmake-scripts.patch
    # - 0002-required-source-changes-for-windows-build.patch

build:
  number: 2
  skip: win

outputs:
  - package:
      name: ${{ name }}

    build:
      script:
        - cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${PREFIX} -DFASTJETCONTRIB_ENABLE_FRAGILELIB=ON
        - if: unix
          then: cmake "${CMAKE_ARGS}" -DCMAKE_INSTALL_PREFIX="${PREFIX}" -S . -B build
        - if: win
          then: cmake %CMAKE_ARGS% -S . -B build
        - cmake -LH build
        - if: unix
          then: cmake --build build --parallel="${CPU_COUNT}"
        - if: win
          then: cmake --build build --config=Release --parallel="%CPU_COUNT%"
        - cmake --install build

    requirements:
      run_exports:
        - ${{ pin_subpackage('fastjet-contrib', upper_bound='x.x') }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - cgal
        - if: unix
          then: make
        - if: build_platform != target_platform
          then:
            - fastjet-cxx
      host:
        - fastjet-cxx
      run:
        - fastjet-cxx

    tests:
      - package_contents:
          lib:
            - fastjetcontribfragile
          include:
            - fastjet/contrib/AxesDefinition.hh
            - fastjet/contrib/BottomUpSoftDrop.hh
            - fastjet/contrib/CMPPlugin.hh
            - fastjet/contrib/Centauro.hh
            - fastjet/contrib/ClusteringVetoPlugin.hh
            - fastjet/contrib/ConstituentSubtractor.hh
            - fastjet/contrib/DistanceMeasure.hh
            - fastjet/contrib/EnergyCorrelator.hh
            - fastjet/contrib/EventStorage.hh
            - fastjet/contrib/ExtraRecombiners.hh
            - fastjet/contrib/FlavInfo.hh
            - fastjet/contrib/FlavNeutraliser.hh
            - fastjet/contrib/FlavorCone.hh
            - fastjet/contrib/GHSAlgo.hh
            - fastjet/contrib/GenericSubtractor.hh
            - fastjet/contrib/IFNPlugin.hh
            - fastjet/contrib/IteratedSoftDrop.hh
            - fastjet/contrib/IterativeConstituentSubtractor.hh
            - fastjet/contrib/JetCleanser.hh
            - fastjet/contrib/JetFFMoments.hh
            - fastjet/contrib/JetsWithoutJets.hh
            - fastjet/contrib/KTClusCXX.hh
            - fastjet/contrib/LundEEHelpers.hh
            - fastjet/contrib/LundGenerator.hh
            - fastjet/contrib/LundJSON.hh
            - fastjet/contrib/LundPlane.hh
            - fastjet/contrib/LundWithSecondary.hh
            - fastjet/contrib/MassFlav.hh
            - fastjet/contrib/MeasureDefinition.hh
            - fastjet/contrib/ModifiedMassDropTagger.hh
            - fastjet/contrib/Njettiness.hh
            - fastjet/contrib/NjettinessPlugin.hh
            - fastjet/contrib/Nsubjettiness.hh
            - fastjet/contrib/QCDAwarePlugin.hh
            - fastjet/contrib/Recluster.hh
            - fastjet/contrib/RecursiveLundEEGenerator.hh
            - fastjet/contrib/RecursiveSoftDrop.hh
            - fastjet/contrib/RecursiveSymmetryCutBase.hh
            - fastjet/contrib/RescalingClasses.hh
            - fastjet/contrib/SDFPlugin.hh
            - fastjet/contrib/ScJet.hh
            - fastjet/contrib/SecondaryLund.hh
            - fastjet/contrib/ShapeWithComponents.hh
            - fastjet/contrib/ShapeWithPartition.hh
            - fastjet/contrib/SignalFreeBackgroundEstimator.hh
            - fastjet/contrib/SoftDrop.hh
            - fastjet/contrib/SoftKiller.hh
            - fastjet/contrib/SubjetCounting.hh
            - fastjet/contrib/TauComponents.hh
            - fastjet/contrib/ValenciaPlugin.hh
            - fastjet/contrib/VariableR.hh
            - fastjet/contrib/VariableRPlugin.hh
            - fastjet/contrib/XConePlugin.hh
      - script: run_test_shared.sh
        requirements:
          run:
            - ${{ compiler('cxx') }}
            - curl
            - tar
            - grep
            - sed


  - package:
      name: ${{ name }}-static

    build:
      script:
        - cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${PREFIX} -DFASTJETCONTRIB_ENABLE_FRAGILELIB=OFF
        - if: unix
          then: cmake "${CMAKE_ARGS}" -DCMAKE_INSTALL_PREFIX="${PREFIX}" -S . -B build
        - if: win
          then: cmake %CMAKE_ARGS% -S . -B build
        - cmake -LH build
        - if: unix
          then: cmake --build build --parallel="${CPU_COUNT}"
        - if: win
          then: cmake --build build --config=Release --parallel="%CPU_COUNT%"
        - cmake --install build

    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - cgal
        - if: unix
          then: make
        - if: build_platform != target_platform
          then:
            - fastjet-cxx
      host:
        - fastjet-cxx
      run:
        - fastjet-cxx

    tests:
      - package_contents:
          lib:
            - CMPPlugin
            - Centauro
            - ClusteringVetoPlugin
            - ConstituentSubtractor
            - EnergyCorrelator
            - FlavorCone
            - GHSAlgo
            - GenericSubtractor
            - IFNPlugin
            - JetCleanser
            - JetFFMoments
            - JetsWithoutJets
            - LundPlane
            - Nsubjettiness
            - QCDAwarePlugin
            - RecursiveTools
            - SDFPlugin
            - ScJet
            - SignalFreeBackgroundEstimator
            - SoftKiller
            - SubjetCounting
            - ValenciaPlugin
            - VariableR
          include:
            - fastjet/contrib/AxesDefinition.hh
            - fastjet/contrib/BottomUpSoftDrop.hh
            - fastjet/contrib/CMPPlugin.hh
            - fastjet/contrib/Centauro.hh
            - fastjet/contrib/ClusteringVetoPlugin.hh
            - fastjet/contrib/ConstituentSubtractor.hh
            - fastjet/contrib/DistanceMeasure.hh
            - fastjet/contrib/EnergyCorrelator.hh
            - fastjet/contrib/EventStorage.hh
            - fastjet/contrib/ExtraRecombiners.hh
            - fastjet/contrib/FlavInfo.hh
            - fastjet/contrib/FlavNeutraliser.hh
            - fastjet/contrib/FlavorCone.hh
            - fastjet/contrib/GHSAlgo.hh
            - fastjet/contrib/GenericSubtractor.hh
            - fastjet/contrib/IFNPlugin.hh
            - fastjet/contrib/IteratedSoftDrop.hh
            - fastjet/contrib/IterativeConstituentSubtractor.hh
            - fastjet/contrib/JetCleanser.hh
            - fastjet/contrib/JetFFMoments.hh
            - fastjet/contrib/JetsWithoutJets.hh
            - fastjet/contrib/KTClusCXX.hh
            - fastjet/contrib/LundEEHelpers.hh
            - fastjet/contrib/LundGenerator.hh
            - fastjet/contrib/LundJSON.hh
            - fastjet/contrib/LundPlane.hh
            - fastjet/contrib/LundWithSecondary.hh
            - fastjet/contrib/MassFlav.hh
            - fastjet/contrib/MeasureDefinition.hh
            - fastjet/contrib/ModifiedMassDropTagger.hh
            - fastjet/contrib/Njettiness.hh
            - fastjet/contrib/NjettinessPlugin.hh
            - fastjet/contrib/Nsubjettiness.hh
            - fastjet/contrib/QCDAwarePlugin.hh
            - fastjet/contrib/Recluster.hh
            - fastjet/contrib/RecursiveLundEEGenerator.hh
            - fastjet/contrib/RecursiveSoftDrop.hh
            - fastjet/contrib/RecursiveSymmetryCutBase.hh
            - fastjet/contrib/RescalingClasses.hh
            - fastjet/contrib/SDFPlugin.hh
            - fastjet/contrib/ScJet.hh
            - fastjet/contrib/SecondaryLund.hh
            - fastjet/contrib/ShapeWithComponents.hh
            - fastjet/contrib/ShapeWithPartition.hh
            - fastjet/contrib/SignalFreeBackgroundEstimator.hh
            - fastjet/contrib/SoftDrop.hh
            - fastjet/contrib/SoftKiller.hh
            - fastjet/contrib/SubjetCounting.hh
            - fastjet/contrib/TauComponents.hh
            - fastjet/contrib/ValenciaPlugin.hh
            - fastjet/contrib/VariableR.hh
            - fastjet/contrib/VariableRPlugin.hh
            - fastjet/contrib/XConePlugin.hh
      - script: run_test_static.sh
        requirements:
          run:
            - ${{ compiler('cxx') }}
            - curl
            - tar
            - grep
            - sed

about:
  homepage: https://fastjet.hepforge.org/contrib/
  summary: 'FastJet Contrib: 3rd party extensions of FastJet'
  description: |
    The fastjet-contrib space is intended to provide a common location for
    access to 3rd party extensions of FastJet.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  repository: https://github.com/fjcontrib/fjcontrib
  documentation: https://fastjet.hepforge.org/contrib/

extra:
  feedstock-name: fastjet-contrib
  recipe-maintainers:
    - kratsg
    - matthewfeickert
    - lgray
